version: '3.1'

services:
  orders:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql