server:
  port: 9999
spring:
  application:
    name: monitoring-service
  boot:
    admin:
      discovery:
        ignored-services: monitoring-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: https://admin:admin@localhost:8761/eureka