server:
  port: 9999
spring:
  application:
    name: monitoring-service
  boot:
    admin:
      discovery:
        ignored-services: monitoring-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://admin:admin@192.168.55.103:8761/eureka
      preferIpAddress: true