server:
  port: 8080
  ssl:
    enabled: true
    key-store: src/main/resources/keys/bootsecurity2.p12
    key-store-password: changeit
    key-store-type: PKCS12
    keyAlias: shop

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/api/product/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/v1/api/auth/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/api/order/**
        - id: shipment-service
          uri: lb://SHIPMENT-SERVICE
          predicates:
            - Path=/v1/api/shipment/**

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://admin:admin@localhost:8761/eureka