server:
  port: 8080
  ssl:
    enabled: true
    key-store: src/main/resources/keys/shop.p12
    key-store-password: changeit
    key-store-type: PKCS12
    keyAlias: ugshop

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/api/product/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/v1/api/auth/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/api/order/**
        - id: order-details-service
          uri: lb://ORDER-DETAILS-SERVICE
          predicates:
            - Path=/v1/api/order-details/**
        - id: shipment-service
          uri: lb://SHIPMENT-SERVICE
          predicates:
            - Path=/v1/api/shipment/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    secure-port-enabled: true
    non-secure-port-enabled: false
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://admin:admin@192.168.55.103:8761/eureka

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,mappings,httpexchanges