version: '3.1'

services:
  product:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql