version: '3.1'

services:
  authentication:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql