version: '3.1'

services:
  shipment:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql